[buildPlans.Iosevka_9L]
family = "Iosevka 9L"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.Iosevka_9L.variants]
  inherits = "ss14"

    [buildPlans.Iosevka_9L.variants.design]
    zero = "long-dotted"
    diacritic-dot = "round"
    punctuation-dot = "round"
    braille-dot = "round"
    asterisk = "hex-low"
    underscore = "above-baseline"
    caret = "low"
    brace = "curly-flat-boundary"
    dollar = "slanted-interrupted"
    percent = "rings-continuous-slash"

  [buildPlans.Iosevka_9L.ligations]
  inherits = "dlig"

[buildPlans.Iosevka_9L.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iosevka_9L.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Iosevka_9L.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.Iosevka_9L.widths.Normal]
shape = 600
menu = 5
css = "normal"
